name: nodo
version: master
summary: Open source geospatial storage server compatible with Amazon S3 APIs
description: |
  Nodo is an geospatial storage server released under Apache License v2.0. It is
  compatible with Amazon S3 cloud storage service. It is best suited for
  storing unstructured data such as photos, videos, log files, backups and
  container / VM images. Size of an object can range from a few KBs to a
  maximum of 5TB. It's a fork of Minio (minio.io) that adds static website
  hosting and support for WFS and STAC.

grade: stable
confinement: strict

apps:
  nodo:
    command: nodo
    plugs:
      - home
      - mount-observe
      - network
      - network-bind
      - network-control
      - removable-media

parts:
  nodo:
    source: .
    plugin: nil
    build-packages: [make,]
    override-build: |     
      mkdir -p ../go/src/github.com/piensa/nodo
      cp -R . ../go/src/github.com/piensa/nodo
      env GOPATH=$(pwd)/../go make -C ../go/src/github.com/piensa/nodo install
      snapcraftctl build
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv ../go/bin/nodo $SNAPCRAFT_PART_INSTALL/bin/
    after: [go]
  go:
    source-tag: go1.10.3
